# Generated by Django 4.2 on 2023-04-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service_name')),
                ('img_service', models.CharField(max_length=1000, verbose_name='Image_service')),
                ('service_text', models.TextField(verbose_name='Service')),
                ('benefits', models.TextField(verbose_name='Benefits')),
                ('routines', models.TextField(verbose_name='Routines')),
                ('warnings', models.TextField(verbose_name='Warnings')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('logo', models.CharField(max_length=1000, verbose_name='Logo')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site_description', models.TextField(verbose_name='Description')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('instagram', models.CharField(max_length=200, verbose_name='Instagram')),
                ('instagram_nick', models.CharField(max_length=50, verbose_name='Instagram @')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('whatsapp', models.CharField(default='https://wa.me/', max_length=100, verbose_name='Link_whatsapp')),
                ('keywords', models.TextField(verbose_name='Keywords')),
                ('img_hero', models.CharField(max_length=1000, verbose_name='Image1')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.CreateModel(
            name='Testemonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer_name')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('testemonial', models.TextField(max_length=1500, verbose_name='Testemonial')),
                ('img_customer', models.CharField(max_length=1000, verbose_name='Customer_img')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
